Added logick for EyeCore. Modified Classification to accommodate new standard for Fundus photography
flywheel-apps/GRP-3B pull request #36
Opened 2020-09-11 23:07 UTC by aldum1

2020-09-11 23:49 UTC, NPann requested changes
Just requesting a change on the manifest version. The rest LGTM. 
A few other minor comments.

2020-09-11 23:49 UTC, NPann commented on manifest.json
> +      "image": "dicom-metadata-classification:1.6.1_sbx_8"
Could revert back this change so that we only increase manifest version upon release?

2020-09-11 23:49 UTC, NPann commented on OPHTHA_classifier.py
> +        if octType == None:
Nit: recommended using `is` in place of `==` when comparing to None.

2020-09-11 23:49 UTC, NPann commented on OPHTHA_classifier.py
> +#     return modality
Leaving these comments on purpose?

2020-09-14 15:09 UTC, jiavila commented
https://github.com/flywheel-apps/GRP-3B/pull/36/files#diff-69d91eb184581109fbaaa14fc06d81d1R23-R27

I think there needs to be a space between two tests, or else it treats it as one. Can you double-check? Thanks!

2020-09-14 16:22 UTC, aldum1 commented
> https://github.com/flywheel-apps/GRP-3B/pull/36/files#diff-69d91eb184581109fbaaa14fc06d81d1R23-R27
> 
> @aldum1 I think there needs to be a space between two tests, or else it treats it as one. Can you double-check? Thanks!

I added spaces, but it looked like it was working without them as well

2020-09-14 16:24 UTC, aldum1 commented on OPHTHA_classifier.py
> +        if octType == None:
updated code to reflect suggestion. Thanks for pointing it out

2020-09-14 16:47 UTC, aldum1 commented
above issues are addressed

2020-09-14 17:25 UTC, jiavila commented
> > https://github.com/flywheel-apps/GRP-3B/pull/36/files#diff-69d91eb184581109fbaaa14fc06d81d1R23-R27
> > @aldum1 I think there needs to be a space between two tests, or else it treats it as one. Can you double-check? Thanks!
> 
> I added spaces, but it looked like it was working without them as well

Good to know. Thanks, Alex!

2020-09-14 22:27 UTC, NPann approved these changes
Thanks Alex for addressing the comments. LGTM.

2020-09-14 22:32 UTC, NPann requested changes
@aldum1 , actually `python -m pytest` is failing on test_pt_classifier.py. Can you fix it so that we can merge it?

2020-09-15 14:43 UTC, kalebdfischer commented
> @aldum1 , actually `python -m pytest` is failing on test_pt_classifier.py. Can you fix it so that we can merge it?

I fixed it in #35 (just merged to master)

2020-09-15 14:47 UTC, kalebdfischer approved these changes
LGTM

2020-09-15 14:48 UTC, NPann approved these changes

2020-09-17 18:22 UTC, merged