Fix for attenuation correction and enabling scan coverage anatomy
flywheel-apps/GRP-3B pull request #49
Opened 2021-05-13 15:56 UTC by bhalchandranoopur

Introduced following updates:
1. Extended MR classification to support Contrast/No Contrast
2. Enabled ScanCoverage based Anatomy classification for PT and CT
3. Fix: Attenuation Correction classification will not be set for PT if 'None' keyword is present in the tag

2021-05-13 16:41 UTC, NPann requested changes
LGTM. Can you just bumped the version accordingly to comment?

2021-05-13 16:41 UTC, NPann commented on manifest.json
> -      "image": "dicom-metadata-classification:1.8.0"
We should bump to 1.9.0 given the added features

2021-05-13 17:35 UTC, bhalchandranoopur commented on manifest.json
> -      "image": "dicom-metadata-classification:1.8.0"
Done! Bumped the version to 1.9.0. Thanks!

2021-05-14 05:22 UTC, NPann approved these changes

2021-05-14 05:24 UTC, merged